import { Ingredient } from './ingredient.model';

export function defaultState() {
  let ingredients: Ingredient[] = [
    {
      "id": "00106e1b",
      "name": "Abecean Longfin",
      "primary": "00073F2E",
      "secondary": "0003EB22",
      "tertiary": "00090042",
      "quaternary": "0003EB28",
      "value": 15,
      "weight": 0.5,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "xx0059ba",
      "name": "Ancestor Moth Wing",
      "primary": "0003A2C6",
      "secondary": "0003EB25",
      "tertiary": "00073F2B",
      "quaternary": "0003EB29",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0006bc02",
      "name": "Bear Claws",
      "primary": "0003EB16",
      "secondary": "0003EAF3",
      "tertiary": "0003EB19",
      "quaternary": "00073F2B",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000a9195",
      "name": "Bee",
      "primary": "0003EB16",
      "secondary": "00073F23",
      "tertiary": "0003EB08",
      "quaternary": "00073F2F",
      "value": 3,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000a9191",
      "name": "Beehive Husk",
      "primary": "00090041",
      "secondary": "0003EB1F",
      "tertiary": "0003EB22",
      "quaternary": "0003EB26",
      "value": 5,
      "weight": 1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0004da20",
      "name": "Bleeding Crown",
      "primary": "00073F2D",
      "secondary": "0003EB1C",
      "tertiary": "00090042",
      "quaternary": "00039E51",
      "value": 10,
      "weight": 0.3,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 3,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0004da25",
      "name": "Blisterwort",
      "primary": "0003A2C6",
      "secondary": "00073F29",
      "tertiary": "0003EB15",
      "quaternary": "0003EB1D",
      "value": 12,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 4,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000727de",
      "name": "Blue Butterfly Wing",
      "primary": "0003A2C6",
      "secondary": "0003EB25",
      "tertiary": "00073F2B",
      "quaternary": "0003EB29",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000e4f0c",
      "name": "Blue Dartwing",
      "primary": "0003EAEC",
      "secondary": "0003EB20",
      "tertiary": "0003EB15",
      "quaternary": "00073F20",
      "value": 1,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00077e1c",
      "name": "Blue Mountain Flower",
      "primary": "0003EB15",
      "secondary": "0003EB25",
      "tertiary": "0003EAF3",
      "quaternary": "00073F2B",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 3,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00034cdd",
      "name": "Bone Meal",
      "primary": "0003A2C6",
      "secondary": "0003EAEA",
      "tertiary": "0003EB25",
      "quaternary": "00073F23",
      "value": 5,
      "weight": 0.5,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad61",
      "name": "Briar Heart",
      "primary": "0003EB17",
      "secondary": "0003EB1C",
      "tertiary": "00073F30",
      "quaternary": "0003EAF8",
      "value": 20,
      "weight": 0.5,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000727e0",
      "name": "Butterfly Wing",
      "primary": "0003EB15",
      "secondary": "0003EB23",
      "tertiary": "0010DE5E",
      "quaternary": "0003A2B6",
      "value": 3,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0006abcb",
      "name": "Canis Root",
      "primary": "0003A2C6",
      "secondary": "0003EB19",
      "tertiary": "0003EB1B",
      "quaternary": "00073F30",
      "value": 5,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 4,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00052695",
      "name": "Charred Skeever Hide",
      "primary": "0003EB16",
      "secondary": "000AE722",
      "tertiary": "00090041",
      "quaternary": "0003EB15",
      "value": 1,
      "weight": 0.5,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad56",
      "name": "Chaurus Eggs",
      "primary": "00090042",
      "secondary": "0003EAF9",
      "tertiary": "0003A2B6",
      "quaternary": "0003EB3D",
      "value": 10,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "xx0183b7",
      "name": "Chaurus Hunter Antennae",
      "primary": "0003A2C6",
      "secondary": "0003EB25",
      "tertiary": "00073F2B",
      "quaternary": "0003EB29",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00023d77",
      "name": "Chicken's Egg",
      "primary": "00039E51",
      "secondary": "00073F2B",
      "tertiary": "0003AC2D",
      "quaternary": "0010DE5E",
      "value": 2,
      "weight": 0.5,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000b2183",
      "name": "Creep Cluster",
      "primary": "0003EB17",
      "secondary": "00073F2C",
      "tertiary": "0003EB01",
      "quaternary": "00073F51",
      "value": 1,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 5,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000b701a",
      "name": "Crimson Nirnroot",
      "primary": "0003EB42",
      "secondary": "0003A2C6",
      "tertiary": "0003EB3D",
      "quaternary": "00039E51",
      "value": 10,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00106e19",
      "name": "Cyrodilic Spadetail",
      "primary": "0003A2C6",
      "secondary": "0003EB28",
      "tertiary": "00073F20",
      "quaternary": "00073F26",
      "value": 15,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad5b",
      "name": "Daedra Heart",
      "primary": "0003EB15",
      "secondary": "00073F2C",
      "tertiary": "0003A2B6",
      "quaternary": "00073F20",
      "value": 250,
      "weight": 0.5,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000516c8",
      "name": "Deathbell",
      "primary": "0003EB42",
      "secondary": "00073F23",
      "tertiary": "00073F25",
      "quaternary": "00090042",
      "value": 4,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 3,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000889a2",
      "name": "Dragon's Tongue",
      "primary": "0003EAEA",
      "secondary": "0003EB23",
      "tertiary": "0003EB27",
      "quaternary": "0003EB1A",
      "value": 5,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 4,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000f11c0",
      "name": "Dwarven Oil",
      "primary": "00073F51",
      "secondary": "0003EB27",
      "tertiary": "0003EB07",
      "quaternary": "0003EB17",
      "value": 15,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad63",
      "name": "Ectoplasm",
      "primary": "0003EB17",
      "secondary": "0003EB26",
      "tertiary": "0003EAF8",
      "quaternary": "0003EB42",
      "value": 25,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00034d31",
      "name": "Elves Ear",
      "primary": "0003EB17",
      "secondary": "0003EB1B",
      "tertiary": "00073F2E",
      "quaternary": "0003EAEA",
      "value": 10,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0006bc07",
      "name": "Eye of Sabre Cat",
      "primary": "0003EB16",
      "secondary": "00073F26",
      "tertiary": "0003A2B6",
      "quaternary": "0003EB15",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad5d",
      "name": "Falmer Ear",
      "primary": "0003EB42",
      "secondary": "00073F29",
      "tertiary": "00090041",
      "quaternary": "0003EB21",
      "value": 10,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad5e",
      "name": "Fire Salts",
      "primary": "00073F2E",
      "secondary": "0003EAEA",
      "tertiary": "0003EB17",
      "quaternary": "0003EB07",
      "value": 50,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0004da00",
      "name": "Fly Amanita",
      "primary": "0003EAEA",
      "secondary": "0003EB1A",
      "tertiary": "00073F29",
      "quaternary": "0003EB08",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 4,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00034d32",
      "name": "Frost Mirriam",
      "primary": "0003EAEB",
      "secondary": "0003EB22",
      "tertiary": "00073F27",
      "quaternary": "00073F2C",
      "value": 1,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad5f",
      "name": "Frost Salts",
      "primary": "00073F2D",
      "secondary": "0003EAEB",
      "tertiary": "0003EB17",
      "quaternary": "0003EB25",
      "value": 100,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00034d22",
      "name": "Garlic",
      "primary": "00090041",
      "secondary": "0003EAF9",
      "tertiary": "0003EB07",
      "quaternary": "0003EB06",
      "value": 1,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0007e8c1",
      "name": "Giant Lichen",
      "primary": "00073F2F",
      "secondary": "00073F26",
      "tertiary": "00090042",
      "quaternary": "0003EB17",
      "value": 5,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 4,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad64",
      "name": "Giant's Toe",
      "primary": "0003A2C6",
      "secondary": "0003EAF3",
      "tertiary": "0003EB01",
      "quaternary": "00073F2C",
      "value": 20,
      "weight": 1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "xx00b097",
      "name": "Gleamblossom",
      "primary": "00039E51",
      "secondary": "00073F20",
      "tertiary": "0003EB06",
      "quaternary": "00073F30",
      "value": 5,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad73",
      "name": "Glow Dust",
      "primary": "0003A2B6",
      "secondary": "00073F2B",
      "tertiary": "0003EB26",
      "quaternary": "0003EAEC",
      "value": 20,
      "weight": 0.5,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0007ee01",
      "name": "Glowing Mushroom",
      "primary": "0003EAEC",
      "secondary": "0003EB26",
      "tertiary": "0003EB1D",
      "quaternary": "0003EAF3",
      "value": 5,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 5,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00083e64",
      "name": "Grass Pod",
      "primary": "00090041",
      "secondary": "00073F27",
      "tertiary": "0003EB24",
      "quaternary": "0003EB17",
      "value": 1,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 3,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0006b689",
      "name": "Hagraven Claw",
      "primary": "00039E51",
      "secondary": "0010DE5F",
      "tertiary": "0003EB29",
      "quaternary": "0003EB23",
      "value": 20,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad66",
      "name": "Hagraven Feathers",
      "primary": "0003A2B6",
      "secondary": "0003EB25",
      "tertiary": "00073F29",
      "quaternary": "00073F2F",
      "value": 20,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00057f91",
      "name": "Hanging Moss",
      "primary": "0003A2B6",
      "secondary": "0003EAF3",
      "tertiary": "00073F2B",
      "quaternary": "0003EB19",
      "value": 1,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000e7ebc",
      "name": "Hawk Beak",
      "primary": "0003EB16",
      "secondary": "0003EAEB",
      "tertiary": "0003EB01",
      "quaternary": "0003EAEC",
      "value": 15,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000e7ed0",
      "name": "Hawk Feathers",
      "primary": "000AE722",
      "secondary": "0003EB1F",
      "tertiary": "0003EB19",
      "quaternary": "0003EB22",
      "value": 15,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "xx00f1cc",
      "name": "Hawk's Egg",
      "primary": "00039E51",
      "secondary": "00073F2B",
      "tertiary": "0003AC2D",
      "quaternary": "0010DE5E",
      "value": 5,
      "weight": 0.5,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00106e18",
      "name": "Histcarp",
      "primary": "0003EB16",
      "secondary": "0003EAF8",
      "tertiary": "00073F2C",
      "quaternary": "0003AC2D",
      "value": 6,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000b08c5",
      "name": "Honeycomb",
      "primary": "0003EB16",
      "secondary": "0003EB1C",
      "tertiary": "0003EB1F",
      "quaternary": "00073F23",
      "value": 5,
      "weight": 1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "001016b3",
      "name": "Human Flesh",
      "primary": "0003EB42",
      "secondary": "00073F30",
      "tertiary": "0003EB17",
      "quaternary": "0003EB22",
      "value": 1,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000b18cd",
      "name": "Human Heart",
      "primary": "0003EB42",
      "secondary": "0003A2B6",
      "tertiary": "00073F2B",
      "quaternary": "00073F29",
      "value": 0,
      "weight": 1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad6a",
      "name": "Ice Wraith Teeth",
      "primary": "00073F2E",
      "secondary": "0003EB1E",
      "tertiary": "0003EB3D",
      "quaternary": "00073F2D",
      "value": 30,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0004da23",
      "name": "Imp Stool",
      "primary": "0003EB42",
      "secondary": "0010AA4A",
      "tertiary": "00073F30",
      "quaternary": "0003EB15",
      "value": 0,
      "weight": 0.3,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 4,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0006ac4a",
      "name": "Jazbay Grapes",
      "primary": "00073F51",
      "secondary": "0003EAF8",
      "tertiary": "0003EB07",
      "quaternary": "00073F26",
      "value": 1,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 3,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0005076e",
      "name": "Juniper Berries",
      "primary": "00073F2D",
      "secondary": "0003EB1B",
      "tertiary": "0003EB06",
      "quaternary": "00073F2C",
      "value": 1,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 4,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0006bc0a",
      "name": "Large Antlers",
      "primary": "0003EB16",
      "secondary": "0003EAF9",
      "tertiary": "00073F25",
      "quaternary": "00073F2C",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00045c28",
      "name": "Lavender",
      "primary": "00039E51",
      "secondary": "0003EAF9",
      "tertiary": "00073F27",
      "quaternary": "0003EB25",
      "value": 1,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 3,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000727df",
      "name": "Luna Moth Wing",
      "primary": "0003A2B6",
      "secondary": "0003EB1F",
      "tertiary": "0003EB06",
      "quaternary": "0003EB3D",
      "value": 5,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000d8e3f",
      "name": "Moon Sugar",
      "primary": "00073F2D",
      "secondary": "0003EAEB",
      "tertiary": "0003EB17",
      "quaternary": "0003EB07",
      "value": 50,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000ec870",
      "name": "Mora Tapinella",
      "primary": "0003EB17",
      "secondary": "0010AA4A",
      "tertiary": "0003EB08",
      "quaternary": "0003EB27",
      "value": 4,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 3,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0006bc00",
      "name": "Mudcrab Chitin",
      "primary": "0003EB16",
      "secondary": "000AE722",
      "tertiary": "00090041",
      "quaternary": "0003EAEA",
      "value": 2,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0004da24",
      "name": "Namira's Rot",
      "primary": "0003A2B6",
      "secondary": "0003EB21",
      "tertiary": "00073F20",
      "quaternary": "0003EB06",
      "value": 0,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 3,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0002f44c",
      "name": "Nightshade",
      "primary": "0003EB42",
      "secondary": "00073F2B",
      "tertiary": "0010DE5E",
      "quaternary": "0003EB26",
      "value": 8,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 3,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00059b86",
      "name": "Nirnroot",
      "primary": "0003EB42",
      "secondary": "0003A2C6",
      "tertiary": "0003EB3D",
      "quaternary": "00039E51",
      "value": 10,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0007edf5",
      "name": "Nordic Barnacle",
      "primary": "0003A2B6",
      "secondary": "0003AC2D",
      "tertiary": "0003EB06",
      "quaternary": "0003EB20",
      "value": 5,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000bb956",
      "name": "Orange Dartwing",
      "primary": "0003EB16",
      "secondary": "00073F27",
      "tertiary": "0003EB20",
      "quaternary": "0010AA4A",
      "value": 1,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000854fe",
      "name": "Pearl",
      "primary": "0003EB16",
      "secondary": "0003EB1C",
      "tertiary": "0003EB17",
      "quaternary": "0003EAEC",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00023d6f",
      "name": "Pine Thrush Egg",
      "primary": "0003EB16",
      "secondary": "0003EB21",
      "tertiary": "00090042",
      "quaternary": "0003EAEC",
      "value": 2,
      "weight": 0.5,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "xx0185fb",
      "name": "Poison Bloom",
      "primary": "0003EB42",
      "secondary": "00073F25",
      "tertiary": "0003EB01",
      "quaternary": "00073F20",
      "value": 5,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0006bc10",
      "name": "Powdered Mammoth Tusk",
      "primary": "0003EB16",
      "secondary": "0003EB22",
      "tertiary": "00073F2D",
      "quaternary": "00073F20",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00077e1e",
      "name": "Purple Mountain Flower",
      "primary": "0003EB16",
      "secondary": "0003EB22",
      "tertiary": "0010DE5F",
      "quaternary": "0003EAEB",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 3,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00077e1d",
      "name": "Red Mountain Flower",
      "primary": "0003EB17",
      "secondary": "00073F27",
      "tertiary": "0003EAF8",
      "quaternary": "0003EB42",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 3,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00106e1a",
      "name": "River Betty",
      "primary": "0003EB42",
      "secondary": "0003EB24",
      "tertiary": "00073F25",
      "quaternary": "0003EB01",
      "value": 15,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0007e8c8",
      "name": "Rock Warbler Egg",
      "primary": "0003EB15",
      "secondary": "0003EB19",
      "tertiary": "0003A2C6",
      "quaternary": "00073F51",
      "value": 2,
      "weight": 0.5,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0006bc04",
      "name": "Sabre Cat Tooth",
      "primary": "0003EB16",
      "secondary": "0003EB1E",
      "tertiary": "0003EB1D",
      "quaternary": "00090042",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "xx003545",
      "name": "Salmon Roe",
      "primary": "0003EB16",
      "secondary": "0003AC2D",
      "tertiary": "0003EAF8",
      "quaternary": "0003EB07",
      "value": 5,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00034cdf",
      "name": "Salt Pile",
      "primary": "00073F51",
      "secondary": "0003EB28",
      "tertiary": "00073F25",
      "quaternary": "0003EB07",
      "value": 2,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0006f950",
      "name": "Scaly Pholiota",
      "primary": "00073F51",
      "secondary": "0003EB27",
      "tertiary": "0003EB08",
      "quaternary": "0003EB01",
      "value": 4,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 5,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00106e1c",
      "name": "Silverside Perch",
      "primary": "0003EB16",
      "secondary": "00073F2C",
      "tertiary": "00073F26",
      "quaternary": "0003EAEB",
      "value": 15,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad6f",
      "name": "Skeever Tail",
      "primary": "00073F2C",
      "secondary": "00073F26",
      "tertiary": "0003EB42",
      "quaternary": "0003EB1F",
      "value": 3,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0007e8c5",
      "name": "Slaughterfish Egg",
      "primary": "00090041",
      "secondary": "0003EB20",
      "tertiary": "0010AA4A",
      "quaternary": "0003EAF9",
      "value": 3,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad70",
      "name": "Slaughterfish Scales",
      "primary": "0003EAEB",
      "secondary": "0010AA4A",
      "tertiary": "0003EB1E",
      "quaternary": "0003EB1C",
      "value": 3,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0006bc0b",
      "name": "Small Antlers",
      "primary": "00090042",
      "secondary": "0003EB28",
      "tertiary": "0010DE5E",
      "quaternary": "0003EB42",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00085500",
      "name": "Small Pearl",
      "primary": "0003EB16",
      "secondary": "0003EB19",
      "tertiary": "0003EB28",
      "quaternary": "0003EAEB",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0001b3bd",
      "name": "Snowberries",
      "primary": "0003EAEA",
      "secondary": "0003EB29",
      "tertiary": "0003EAEB",
      "quaternary": "0003EAEC",
      "value": 4,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 4,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0009151b",
      "name": "Spider Egg",
      "primary": "0003A2C6",
      "secondary": "00073F2B",
      "tertiary": "0003EB21",
      "quaternary": "0003EB1B",
      "value": 5,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "00063b5f",
      "name": "Spriggan Sap",
      "primary": "00073F2B",
      "secondary": "0003EB29",
      "tertiary": "0003EB1D",
      "quaternary": "0003EB24",
      "value": 15,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0007e8b7",
      "name": "Swamp Fungal Pod",
      "primary": "0003EAEC",
      "secondary": "0010DE5F",
      "tertiary": "00073F30",
      "quaternary": "0003EB15",
      "value": 5,
      "weight": 0.25,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 3,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad71",
      "name": "Taproot",
      "primary": "00073F51",
      "secondary": "0003EB27",
      "tertiary": "0003EB07",
      "quaternary": "0003EB17",
      "value": 15,
      "weight": 0.5,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "000134aa",
      "name": "Thistle Branch",
      "primary": "0003EAEB",
      "secondary": "00073F23",
      "tertiary": "00090041",
      "quaternary": "0003EB1E",
      "value": 1,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 3,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0004da73",
      "name": "Torchbug Thorax",
      "primary": "0003EB16",
      "secondary": "0010DE5F",
      "tertiary": "00073F51",
      "quaternary": "0003EAF9",
      "value": 1,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad72",
      "name": "Troll Fat",
      "primary": "00090041",
      "secondary": "0003EB1A",
      "tertiary": "00073F29",
      "quaternary": "0003EB42",
      "value": 15,
      "weight": 1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003f7f8",
      "name": "Tundra Cotton",
      "primary": "00039E51",
      "secondary": "0003EAF8",
      "tertiary": "0003EB1C",
      "quaternary": "0003EB23",
      "value": 1,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 3,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad76",
      "name": "Vampire Dust",
      "primary": "0003EB3D",
      "secondary": "0003EB17",
      "tertiary": "0003EB06",
      "quaternary": "000AE722",
      "value": 25,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0003ad60",
      "name": "Void Salts",
      "primary": "00073F2F",
      "secondary": "00039E51",
      "tertiary": "0003EB42",
      "quaternary": "0003EAF8",
      "value": 125,
      "weight": 0.2,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0004b0ba",
      "name": "Wheat",
      "primary": "0003EB15",
      "secondary": "0003EAF3",
      "tertiary": "00073F2C",
      "quaternary": "0010DE5F",
      "value": 5,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 4,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0004da22",
      "name": "White Cap",
      "primary": "00073F2E",
      "secondary": "0003EB1E",
      "tertiary": "0003EB17",
      "quaternary": "00073F27",
      "value": 0,
      "weight": 0.3,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": 2,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "0006bc0e",
      "name": "Wisp Wrappings",
      "primary": "0003EB16",
      "secondary": "0003EB26",
      "tertiary": "0003EB01",
      "quaternary": "00039E51",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    },
    {
      "id": "xx002a78",
      "name": "Yellow Mountain Flower",
      "primary": "00090041",
      "secondary": "0003EB28",
      "tertiary": "0003EAF3",
      "quaternary": "00073F2C",
      "value": 2,
      "weight": 0.1,
      "availability": undefined,
      "availabilityIfPerk": undefined,
      "dlcAvailability": undefined,
      "garden": undefined,
      "unique": undefined,
      "uespLink": undefined,
      "owned": false
    }
  ]
  

   return ingredients;
}